hash-format = "sha256"

[[files]]
file = "config/default-hotkeys.json"
hash = "67aadf146b631a7dd10bda1fbe6f86db9a97076191caca610c6dd91a792e6b8c"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "2492a7266fab4c2ff411612180974b98510afb66a18e640f4de63ad615dd1e9e"
metafile = true

[[files]]
file = "mods/balm-fabric.pw.toml"
hash = "13ac60a79ecbd89dadcf7397e3a19b6363e93d293a0632efa553c54562f8ce7d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
hash = "3771ae493844608b70847d7489a43f91077f6db20e46f89437e2d5c286d4e021"
metafile = true

[[files]]
file = "mods/construction-wand-fabric.pw.toml"
hash = "be724a919a77c63d5184367cb4fe669b4ecf812e1faf71513751c6facae4f4ce"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "e7513fdc9b93652c928a5af59e9dc6a5b21dfe5200fe78883a6fa56d3cdefa1f"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "85c6474576e5ae7c59c2b685e7484c305789df16a91fb6c971684f5f45e120ea"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "4463005ad6ae41db2bf707952d6945297f48601a42ec8b6cac8aef09d653ffd2"
metafile = true

[[files]]
file = "mods/defaulted-hotkeys.pw.toml"
hash = "a0e70470f8734882ab10791cf6dcafd9eda65d37f2dfc92e860a8fd98789f6a8"
metafile = true

[[files]]
file = "mods/deltaboxlib.pw.toml"
hash = "d5141803f665e0525f4da5612b9bafe9c0b3f749104eeb0ed0abde83a60050d8"
metafile = true

[[files]]
file = "mods/dungeonz.pw.toml"
hash = "8f8947aa03c4ac3ee487822e17ad3f990353c11fb3cfc050f564b0ef6e2cd560"
metafile = true

[[files]]
file = "mods/easy-npc-config-ui.pw.toml"
hash = "f13d5af6bd8df9643f54fb8e7563d72697c1b36f3651a78fa17e31b55c3957eb"
metafile = true

[[files]]
file = "mods/easy-npc-core.pw.toml"
hash = "3c1da22a33ba74ddc84f3a3ec2fa04dffedbcda0727549b93b3f0a1f06bbaa83"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "1ee56d5feb0ede9397b26f3c5b7543a3556088146d154b55172ef0e8b1a97705"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "1aa94f817646eea69478dc3dce662c3f4b674359d7ce34cf58fd38dcbc56e458"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "8fe2cb6a509cd81553bd5b20f19585decf8ca2beb3ae6098ce8b65517873e6b7"
metafile = true

[[files]]
file = "mods/ftb-library-fabric.pw.toml"
hash = "36cef0788ba915e48a0fd991847c35056bdbacda46273840c6f300b8431dfdc5"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "d3237427c060742b9b724e0a65d57074c430f06d4f3dadf857ea5252602c8fe4"
metafile = true

[[files]]
file = "mods/keybind-fix.pw.toml"
hash = "1567dc7a6628a5aed513e6c1804d3e3e5b78510d5ac1732ddefee2ce1069f746"
metafile = true

[[files]]
file = "mods/konkrete-fabric.pw.toml"
hash = "34f9d95129ee85e65fb0c4c982b76c247bb11b59ca5bf50a84dd5daae33c51f6"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "2af509457d13907cf0b48f2f0997750c07e0349f6522b87f8b4bcd1794aa2559"
metafile = true

[[files]]
file = "mods/mmmmmmmmmmmm.pw.toml"
hash = "7b05b774f6fa69d4411c807f775285b6a46270acee5320aefac1c8e523892420"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "1b4f637283c0c4e87d642641338dee78b0357b97fbc62fe69911cee8d0b557dc"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5553f08402ff3f277f68bf132463f187d14e2b12275ae319f934e4672f4b9288"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "9a0ab52020c3a2d073e71f07ce11b9d2d8ae0a17b8a3cf0c9227029a51df51c3"
metafile = true

[[files]]
file = "mods/patchouli-fabric.pw.toml"
hash = "12216fa20f72f411ba04636f58a712e925f0ed8c219e140a977a1a95d7fd6ccf"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "3c2fe6485d980a094a5094263d9d54dd59bd4cfd37439109be561894342a82f8"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
hash = "9e26bfad609bded0b1ed972a4cb6ed0bd66fdecd352970ffee6b50dd6a81b4fb"
metafile = true

[[files]]
file = "mods/platform.pw.toml"
hash = "e3eca1d3e47062e831399aa0d4575e3ee2c2d4c649184498fda00d24b1b09626"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "ead2bfc6e6fa3d1f1d82a7f4968ab2c8a712866d635d1875f02936f9ad8aef02"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "286cf1d4aca340479b10c51874cd7cbdb13559140c846bbe9270e3f6f8fc528c"
metafile = true

[[files]]
file = "mods/roughly-enough-professions-rep.pw.toml"
hash = "1b20f1b5ebefb4a1561cc92f775dcfd22d3986a14e56b5f239e0369f0ee3f2f4"
metafile = true

[[files]]
file = "mods/roughly-enough-resources.pw.toml"
hash = "5221fe509420e0ac4908dbd0a050cb905e4c3c5207b1b3e35da264a006619262"
metafile = true

[[files]]
file = "mods/roughly-enough-trades.pw.toml"
hash = "e1abc00feb5b3b95c6dadc4a477bf239d73eb10df6cd5ece514bc42a1341be2c"
metafile = true

[[files]]
file = "mods/sdm-economy.pw.toml"
hash = "3012b7745d746899623aff1e0c5c4f8110e82b49272da68334bdaf26156b65a5"
metafile = true

[[files]]
file = "mods/sdm-market.pw.toml"
hash = "188d2781240441e291bc4a238ec1ff462c161c121a26afa2efd37eb7cb70e538"
metafile = true

[[files]]
file = "mods/sdm-shop.pw.toml"
hash = "fca21401fe7edd6f1f0d8d3deb083bd93420513d98e0c24cb6279335004b8e15"
metafile = true

[[files]]
file = "mods/sdm-ui-lib.pw.toml"
hash = "1d63b212c38f734529e4ae6c1f8e611537494e58ea47fb6e3144612995cdd6bc"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "98739e44d0a6e97c0776861a551cf689d9190a215640210007dd28d3edad9107"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "0ef0506c9ef630f706d8f70c954af05c52799244c3af5183dc552f1175e9701a"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "3a8a6633019f8091cd35a20fa8a96716ba19f2bfe3b79cf6239109f25d557f3e"
metafile = true

[[files]]
file = "mods/terrablender-fabric.pw.toml"
hash = "b69ac7037683a4ff97a93efb144075708409de8207d6572d56dbcc69c2025445"
metafile = true

[[files]]
file = "mods/thematic-api.pw.toml"
hash = "7e54880a90281dc1dea1bd713fcfc85e9bf83d831c9858b9a77aa4184b1c8608"
metafile = true

[[files]]
file = "mods/thematic-superheroes.pw.toml"
hash = "949b0e5cffa60a17bc54d66c2a61c79db2e2b215e69adebc074a0d58ec1cf771"
metafile = true

[[files]]
file = "mods/toms-storage-fabric.pw.toml"
hash = "a4cfb5083b9d014b87293d694d62f61ba3c64c6903885d7c1d46f46cc581f589"
metafile = true

[[files]]
file = "mods/vics-point-blank.pw.toml"
hash = "d85f3ddb66e186c357039435246da7554c26c93889992dcfc8cf30cf608e3145"
metafile = true

[[files]]
file = "pointblank/Cyberpunk_2077_Guns_Pack_1.17.2.zip"
hash = "ea83a299506a81ec5cc3f7e0039e6d9199f21af0698b3d15f8320da92442f32f"

[[files]]
file = "pointblank/README.md"
hash = "cf7d4c0015bfb4fcb9fb96b214b1e4005e53e7dac95d11fa582688bc3e3d2437"

[[files]]
file = "pointblank/RedDeadWeaponry.zip"
hash = "0ebb1c22f9438e8a0f0ba08a3256c94b1460e2df8a0cfc6d77a76a67e630b11b"

[[files]]
file = "pointblank/doom-ext v1.3.5.zip"
hash = "3ac4ab8075c70a73a0bb713b46153cf2c24ad6dac63327a2e7249dcee1f1f62b"

[[files]]
file = "pointblank/halflife-ext 0.7.zip"
hash = "747ef59203d18df7b17c99c7bc59087390b576581f8e4baefc213e871ba6a178"
