name = "thematipack-fabric"
author = "funalex"
version = "1.5.51"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0c36f05df62353c963ae75ace42f00bd1687694449c360867b36054e65063d4"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
